services:
  trailview-process:
    build: .
    environment:
      - IMAGES_PATH=/trails
      - WEB_URL=${WEB_URL}
      - WEB_API_KEY=${WEB_API_KEY}
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /home/mjo1/test-trails:/trails
      - ./docker/logs:/app/logs
