services:
  trailview-web:
    build:
      context: ../
      dockerfile: ./web/Dockerfile
    environment:
      TV_DB_USER: ${TV_DB_USER}
      TV_DB_PASSWORD: ${TV_DB_PASSWORD}
      TV_DB_HOST: trailview-db
      TV_DB_PORT: 5432
      TV_DB_DATABASE: ${TV_DB_DATABASE}
      TV_IMAGES_PATH: /trails
      TV_ADMIN_USER: ${TV_ADMIN_USER}
      TV_ADMIN_PASSWORD: ${TV_ADMIN_PASSWORD}
      PUBLIC_TV_MAPBOX_KEY: ${PUBLIC_TV_MAPBOX_KEY}
      PUBLIC_TV_MAPS_API: ${PUBLIC_TV_MAPS_API}
      ORIGIN: ${ORIGIN}
      PORT: 3000
    ports:
      - ${TV_DOCKER_PORT_EXTERNAL}:3000
    restart: unless-stopped
    volumes:
      - ${TV_DOCKER_IMAGES_MOUNT_PATH}:/trails
      - ./logs:/app/web/logs
    depends_on:
      - trailview-db
  trailview-db:
    image: 'postgis/postgis:16-3.4'
    container_name: 'trailview-db'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TV_DB_DATABASE}
      POSTGRES_USER: ${TV_DB_USER}
      POSTGRES_PASSWORD: ${TV_DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
